# Generated by Django 4.0.2 on 2023-08-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.IntegerField()),
                ('customer_address', models.TextField()),
                ('customer_Identity', models.TextField()),
                ('customer_gst', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=100)),
                ('sensor_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive')], max_length=20)),
                ('sensor_value', models.TextField()),
                ('sensor_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('flag', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.customer')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
    ]
